apiVersion: v1
kind: Service
metadata:
  name: chain-client-evm-polygon-server-966
  namespace: "{{.Deployment.Namespace}}"
spec:
  selector:
    app: chain-client-evm-polygon-966
  type: ClusterIP
  ports:
    - protocol: TCP
      name: chain-client-evm-polygon-api-966
      port: 9100
      targetPort: 9100
---
# Source: chain-client-evm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chain-client-evm-polygon-966
  namespace: "{{.Deployment.Namespace}}"
  labels:
    app: chain-client-evm-polygon-966
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chain-client-evm-polygon-966
  template:
    metadata:
      labels:
        app: chain-client-evm-polygon-966
    spec:
      containers:
        - name: chain-client-evm-polygon-966
          image: "{{.Deployment.Image}}"
          ports:
            - containerPort: {{ if .Deployment.ContainerPort }}{{.Deployment.ContainerPort}}{{ else }}9100{{ end }}
          env:
            - name: CLEAR_PADDING
              value: 'true'
            - name: "STATUS_KEY"
              value: "chain-client-status-report-{{.Deployment.Name}}"
            - name: CHAIN_TYPE
              value: "evm"
            {{range .Deployment.CustomEnv}}
            - name: "{{.Key}}"
              value: "{{.Value}}"
            {{end}}
            - name: REDIS_PASSWORD
              value: "{{.Deployment.RedisPass}}"
            - name: EVM_CLIENT_PORT
              value: "9100"
            - name: REDIS_HOST
              value: "{{.Deployment.RedisHost}}"
            - name: REDIS_PORT
              value: "{{.Deployment.RedisPort}}"
            - name: SYSTEM_CHAIN_ID
              value: "966"
            - name: CHAIN_ID
              value: "80001"
            - name: OS_API_KEY
              value: "{{.Deployment.OsApiKey}}"
            - name: OS_API_SECRET
              value: "{{.Deployment.OsApiSecret}}"
            - name: OS_SYSTEM_SERVER
              value: "{{.Deployment.OsSystemServer}}"
            - name: CONTRACT_ADDRESS
              value: "0xd116c529E3188be0C1E6B53Ee499229e29B1E6fA"
            - name: START_BLOCK
              value: "{{ if .Deployment.StartBlock }}{{.Deployment.StartBlock}}{{ else }}24345141{{ end }}"
            - name: RPC_URL
              value: "{{ if .Deployment.RpcUrl }}{{.Deployment.RpcUrl}}{{ else }}https://polygon-mumbai.blockpi.network/v1/rpc/public{{ end }}"
            - name: START_TOP_HEIGHT
              value: 'true'
            - name: AUTO_START
              value: "false"
# START_BLOCK
# RPC_URL
# image
# image = {{.Deployment.Image}}
