apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    meta.helm.sh/release-name: otmoiclp
    meta.helm.sh/release-namespace: otmoiclp-vaughnmedellins394
  creationTimestamp: "2024-05-06T06:20:12Z"
  generation: 5
  labels:
    app: amm-market-price
    app.kubernetes.io/managed-by: Helm
  name: amm-market-price
  namespace: otmoiclp-vaughnmedellins394
  resourceVersion: "9138635"
  uid: f5649885-9cd1-4f17-862c-7770497f0456
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: amm-market-price
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubesphere.io/restartedAt: "2024-05-07T08:58:12.016Z"
      creationTimestamp: null
      labels:
        app: amm-market-price
    spec:
      containers:
      - env:
        - name: STATUS_KEY
          value: amm-market-status-report-price
        - name: REDIS_HOST
          value: redis-cluster-proxy.user-system-vaughnmedellins394
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: EJtetarG2IAqYX8P
        - name: SERVICE_PORT
          value: "18080"
        - name: MONGODB_HOST
          value: mongo-cluster-mongos.user-system-vaughnmedellins394
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_ACCOUNT
          value: root-vaughnmedellins394-otmoiclp
        - name: MONGODB_PASS
          value: ANqAGivxFeLrEvgO
        - name: MONGODB_DBNAME_LP_STORE
          value: otmoiclp-vaughnmedellins394_lp_store
        - name: WRITE_FILELOG
          value: "true"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: otmoic/lpnode-exchange-adapter:604ccbdd
        imagePullPolicy: Always
        name: amm-market-price
        ports:
        - containerPort: 18080
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-05-06T06:21:10Z"
    lastUpdateTime: "2024-05-06T06:21:10Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-05-06T06:20:12Z"
    lastUpdateTime: "2024-05-07T09:01:14Z"
    message: ReplicaSet "amm-market-price-64778bbfb9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
