apiVersion: v1
kind: Service
metadata:
  name: obridge-chain-client-near-server-397
  namespace: ""
spec:
  selector:
    app: obridge-chain-client-near-397
  type: ClusterIP
  ports:
    - protocol: TCP
      name: obridge-chain-client-near-api-397
      port: 9100
      targetPort: 9100
---
# Source: obridge-chain-client-near/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obridge-chain-client-near-397
  namespace: ""
  labels:
    app: obridge-chain-client-near-397
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obridge-chain-client-near-397
  template:
    metadata:
      labels:
        app: obridge-chain-client-near-397
    spec:
      containers:
        - name: obridge-chain-client-near-397
          image: "kldtks/edge:obridge-chain-client-near-37b587b2"
          ports:
            - containerPort: 9100
          env:
            - name: REDIS_PASSWORD
              value: "{{.Deployment.RedisPass}}"
            - name: NEAR_CLIENT_PORT
              value: "9100"
            - name: REDIS_HOST
              value: "{{.Deployment.RedisHost}}"
            - name: REDIS_PORT
              value: "{{.Deployment.RedisPort}}"
            - name: CONTRACT_ADDRESS
              value: "obridge.near"
            - name: SYSTEM_CHAIN_ID
              value: "397"
            - name: LAKE_BUCKET
              value: "near-lake-data-mainnet"
            - name: LAKE_REGION
              value: "eu-central-1"
            - name: LAKE_POOLSIZE
              value: "200"
            - name: CONNECTION_NETWORKID
              value: "mainnet"

            - name: CONNECTION_NODEURL
              value: "https://rpc.testnet.near.org"
            - name: CONNECTION_WALLETURL
              value: "https://wallet.testnet.near.org"
            - name: CONNECTION_HELPERURL
              value: "https://helper.testnet.near.org"
            - name: CONNECTION_EXPLORERURL
              value: "https://explorer.testnet.near.org"
            - name: AWS_ACCESS_KEY_ID
              value: ""
            - name: AWS_SECRET_ACCESS_KEY
              value: ""
            - name: START_BLOCK
              value: "100"
