apiVersion: apps/v1
kind: Deployment
metadata:
  name: "obridge-amm-amm01"
  labels:
    app: "obridge-amm-amm01"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "obridge-amm-amm01"
  template:
    metadata:
      labels:
        app: "obridge-amm-amm01"
    spec:
      containers:
        - name: "obridge-amm-amm01"
          image: "kldtks/edge:otmoic-lpnode-amm-edd840f7"
          ports:
            - containerPort: 18081
          env:
            - name: "STATUS_KEY"
              value: "obridge-amm-status-report-amm01"
            
            - name: "keyA"
              value: "value2"
            
            - name: "keyb"
              value: "value3"
            
            - name: APP_NAME
              value: "amm01"
            - name: APP_VERSION
              value: "kldtks/edge:otmoic-lpnode-amm-edd840f7"
            - name: OBRIDGE_LPNODE_DB_REDIS_MASTER_SERVICE_HOST
              value: "obridge-lpnode-db-redis-master"
            - name: LP_NODE_DATA_MONGO_URL
              value: "obridge-lpnode-db-mongodb"
            - name: NODE_ENV
              value: "production"
            - name: LP_MARKET_SERVICE_URL
              value: "obridge-lpnode-market"
            - name: "LP_ADMIN_PANEL_ACCESS_BASEURL"
              value: "http://lpnode-admin-server:18006"
            - name: MONGODBPASS
              valueFrom:
                secretKeyRef:
                  name: obridge-lpnode-db-mongodb
                  key: mongodb-root-password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: obridge-lpnode-db-redis
                  key: redis-password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "obridge-amm-amm01-analyze"
  labels:
    app: "obridge-amm-amm01-analyze"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "obridge-amm-amm01-analyze"
  template:
    metadata:
      labels:
        app: "obridge-amm-amm01-analyze"
    spec:
      containers:
        - name: "obridge-amm-amm01-analyze"
          image: "kldtks/edge:otmoic-lpnode-amm-edd840f7"
          env:
            - name: APP_NAME
              value: "kldtks/edge:otmoic-lpnode-amm-analyze-latest"
            - name: APP_VERSION
              value: "kldtks/edge:otmoic-lpnode-amm-analyze-latest"
            - name: OBRIDGE_LPNODE_DB_REDIS_MASTER_SERVICE_HOST
              value: "obridge-lpnode-db-redis-master"
            - name: LP_NODE_DATA_MONGO_URL
              value: "obridge-lpnode-db-mongodb"
            - name: NODE_ENV
              value: "production"
            - name: "LP_ADMIN_PANEL_ACCESS_BASEURL"
              value: "http://lpnode-admin-server:18006"
            - name: MONGODBPASS
              valueFrom:
                secretKeyRef:
                  name: obridge-lpnode-db-mongodb
                  key: mongodb-root-password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: obridge-lpnode-db-redis
                  key: redis-password