apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "weihongjie"
  namespace: "otmoiclp-bigdog"
spec:
  schedule: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: user-script
              persistentVolumeClaim:
                claimName: user-moniter-script
          containers:
          - name: "weihongjie"
            image: kldtks/edge:otmoic-lpnode-monitor-c96d4564
            volumeMounts:
              - name: user-script
                mountPath: /user-script
            imagePullPolicy: IfNotPresent
            env:
            - name: REDIS_PASSWORD
              value: "{{.Deployment.RedisPass}}"
            - name: MONGODB_ROOT_PASSWORD
              value: "{{.Deployment.MongodbPass}}"
            - name: REDIS_HOST
              value: obridge-lpnode-db-redis-master
            - name: MONGODB_HOST
              value: obridge-lpnode-db-mongodb
            command:
            - /bin/sh
            - -c
            - date; node dist/m_c_execute.js --script=user_script_1690882328978823000.js
          restartPolicy: Never