apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{.Name}}"
  namespace: "otmoiclp-bigdog"
spec:
  schedule: "{{.Cron}}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: user-script
              persistentVolumeClaim:
                claimName: user-moniter-script
          containers:
          - name: "{{.Name}}"
            image: kldtks/edge:otmoic-lpnode-monitor-c96d4564
            volumeMounts:
              - name: user-script
                mountPath: /user-script
            imagePullPolicy: IfNotPresent
            env:
            - name: REDIS_PASSWORD
              value: "{{.Deployment.RedisPass}}"
            - name: MONGODB_ROOT_PASSWORD
              value: "{{.Deployment.MongodbPass}}"
            - name: REDIS_HOST
              value: obridge-lpnode-db-redis-master
            - name: MONGODB_HOST
              value: obridge-lpnode-db-mongodb
            command:
            - /bin/sh
            - -c
            - date; node dist/m_c_execute.js --script={{.ScriptPath}}
          restartPolicy: Never