apiVersion: batch/v1
kind: Job
metadata:
  name: "user-once-script-run-{{.JobName}}"
  namespace: "otmoiclp-bigdog"
spec:
  template:
    spec:
      volumes:
        - name: user-script
          persistentVolumeClaim:
            claimName: user-moniter-script
      containers:
      - name: "user-once-script-run-{{.JobName}}"
        image: kldtks/edge:otmoic-lpnode-monitor-c96d4564
        volumeMounts:
          - name: user-script
            mountPath: /user-script
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: obridge-lpnode-db-redis
              key: redis-password
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: obridge-lpnode-db-mongodb
              key: mongodb-root-password
        - name: REDIS_HOST
          value: obridge-lpnode-db-redis-master
        - name: MONGODB_HOST
          value: obridge-lpnode-db-mongodb
        command:
        - /bin/sh
        - -c
        - date; node dist/m_c_execute.js --script={{.ScriptName}} --module=execute
      restartPolicy: Never