apiVersion: batch/v1
kind: Job
metadata:
  name: "user-once-script-run-tmp-script-1690530758142992000"
  namespace: "otmoiclp-bigdog"
spec:
  template:
    spec:
      volumes:
        - name: user-script
          persistentVolumeClaim:
            claimName: user-moniter-script
      containers:
      - name: "user-once-script-run-tmp-script-1690530758142992000"
        image: kldtks/edge:otmoic-lpnode-monitor-bb5d243f
        volumeMounts:
          - name: user-script
            mountPath: /user-script
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: obridge-lpnode-db-redis
              key: redis-password
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: obridge-lpnode-db-mongodb
              key: mongodb-root-password
        - name: REDIS_HOST
          value: obridge-lpnode-db-redis-master
        - name: MONGODB_HOST
          value: obridge-lpnode-db-mongodb
        command:
        - /bin/sh
        - -c
        - date; node dist/m_c_execute.js --script=tmp-script-1690530758142992000.js --module=execute
      restartPolicy: Never