apiVersion: v1
kind: Service
metadata:
  name: "obridge-amm-market-{{.Deployment.Name}}-service"
  namespace: "{{.Deployment.Namespace}}"
spec:
  selector:
    app: "obridge-amm-market-{{.Deployment.Name}}"
  type: ClusterIP
  ports:
    - protocol: TCP
      name: obridge-amm-market-{{.Deployment.Name}}-service
      port: {{ if .Deployment.ContainerPort }}{{.Deployment.ContainerPort}}{{ else }}18080{{ end }}
      targetPort: {{ if .Deployment.ContainerPort }}{{.Deployment.ContainerPort}}{{ else }}18080{{ end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "obridge-amm-market-{{.Deployment.Name}}"
  labels:
    app: "obridge-amm-market-{{.Deployment.Name}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "obridge-amm-market-{{.Deployment.Name}}"
  template:
    metadata:
      labels:
        app: "obridge-amm-market-{{.Deployment.Name}}"
    spec:
      containers:
        - name: "obridge-amm-market-{{.Deployment.Name}}"
          image: "{{.Deployment.Image}}"
          ports:
            - containerPort: {{ if .Deployment.ContainerPort }}{{.Deployment.ContainerPort}}{{ else }}18080{{ end }}
          env:
            - name: "STATUS_KEY"
              value: "obridge-amm-market-status-report-{{.Deployment.Name}}"
            - name: OBRIDGE_LPNODE_DB_REDIS_MASTER_SERVICE_HOST
              value: "{{.Deployment.RedisHost}}"
            - name: LP_NODE_DATA_MONGO_URL
              value: "{{.Deployment.MongodbHost}}"
            - name: REDIS_PORT
              value: "{{.Deployment.RedisPort}}"
            - name: MONGODB_PASS
              value: "{{.Deployment.MongodbPass}}"
            - name: REDIS_PASSWORD
              value: "{{.Deployment.RedisPass}}"
            {{range .Deployment.CustomEnv}}
            - name: "{{.Key}}"
              value: "{{.Value}}"
            {{end}}
            - name: "GO_ENV"
              value: "production"
            - name: "SERVICE_PORT"
              value: "{{ if .Deployment.ContainerPort }}{{.Deployment.ContainerPort}}{{ else }}18080{{ end }}"
            - name: MONGODB_HOST
              value: "{{.Deployment.MongodbHost}}"
            - name: MONGODB_ACCOUNT
              value: "{{.Deployment.MongodbAccount}}"
            - name: MONGODB_DBNAME_LP_STORE
              value: "{{.Deployment.MongodbDbnameLpStore}}"
            - name: MONGODB_PORT
              value: "{{.Deployment.MongodbDbnameHistory}}"
