apiVersion: v1
kind: Service
metadata:
  name: "obridge-amm-market-{{.Deployment.Name}}-service"
  namespace: "{{.Deployment.Namespace}}"
spec:
  selector:
    app: "obridge-amm-market-{{.Deployment.Name}}"
  type: ClusterIP
  ports:
    - protocol: TCP
      name: obridge-amm-market-{{.Deployment.Name}}-service
      port: {{ if .Deployment.ContainerPort }}{{.Deployment.ContainerPort}}{{ else }}18080{{ end }}
      targetPort: {{ if .Deployment.ContainerPort }}{{.Deployment.ContainerPort}}{{ else }}18080{{ end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "obridge-amm-market-{{.Deployment.Name}}"
  labels:
    app: "obridge-amm-market-{{.Deployment.Name}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "obridge-amm-market-{{.Deployment.Name}}"
  template:
    metadata:
      labels:
        app: "obridge-amm-market-{{.Deployment.Name}}"
    spec:
      containers:
        - name: "obridge-amm-market-{{.Deployment.Name}}"
          image: "{{.Deployment.Image}}"
          ports:
            - containerPort: {{ if .Deployment.ContainerPort }}{{.Deployment.ContainerPort}}{{ else }}18080{{ end }}
          env:
            - name: "STATUS_KEY"
              value: "obridge-amm-market-status-report-{{.Deployment.Name}}"
            - name: OBRIDGE_LPNODE_DB_REDIS_MASTER_SERVICE_HOST
              value: "obridge-lpnode-db-redis-master"
            - name: LP_NODE_DATA_MONGO_URL
              value: "obridge-lpnode-db-mongodb"
            - name: MONGODBPASS
              valueFrom:
                secretKeyRef:
                  name: obridge-lpnode-db-mongodb
                  key: mongodb-root-password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: obridge-lpnode-db-redis
                  key: redis-password
            {{range .Deployment.CustomEnv}}
            - name: "{{.Key}}"
              value: "{{.Value}}"{{end}}
            - name: "GO_ENV"
              value: "production"
            - name: "SERVICE_PORT"
              value: "{{ if .Deployment.ContainerPort }}{{.Deployment.ContainerPort}}{{ else }}18080{{ end }}"
